# Generated by Django 4.2.3 on 2023-07-31 18:10

from django.db import migrations, models
import media_land.media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_medialanduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialanduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos', validators=[media_land.media.validators.validate_file_size]),
        ),
    ]
