# Generated by Django 4.2.3 on 2023-07-31 15:48

from django.db import migrations, models
import media_land.media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_image',
            field=models.ImageField(upload_to='media', validators=[media_land.media.validators.validate_file_size]),
        ),
    ]
