# Generated by Django 4.2.3 on 2023-07-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_media_link_alter_media_media_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='media_link',
            new_name='link',
        ),
    ]
